bookrevs/bookrevs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('admin/', admin.site.urls),
    path('reviews/', include(('reviews.urls', 'reviews'), namespace='reviews')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/', include('django.contrib.auth.urls')),    
    
]

bookrevs/reviews/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    

    # ex: /
    url(r'^$', views.review_list, name='review_list'),

    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),

    # ex: /book/
    url(r'^book$', views.book_list, name='book_list'),

    # ex: /book/5/
    url(r'^book/(?P<book_id>[0-9]+)/$', views.book_detail, name='book_detail'),
    url(r'^book/(?P<book_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),

    # ex: /review/user - get reviews for the logged user
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),

]

bookrevs/reviews/models.py
from django.db import models

from django.db.models import Avg

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200, default='Anonymous')
    
    def average_rating(self):
        return self.review_set.aggregate(Avg('rating'))['rating__avg']
        
    def __unicode__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    
    book = models.ForeignKey(Book, on_delete=models.DO_NOTHING,)
    
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)
    

bookrevs/reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        
        model = Review
        fields = ['rating', 'comment','user_name']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

bookrevs/reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Review, Book
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required
import datetime



def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def book_list(request):
    book_list = Book.objects.order_by('-name')
    context = {'book_list':book_list}
    return render(request, 'reviews/book_list.html', context)


def book_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = ReviewForm()
    return render(request, 'reviews/book_detail.html', {'book': book, 'form': form})
    
@login_required
def add_review(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = form.cleaned_data['user_name']
        user_name = request.user.username
        review = Review()
        review.book = book
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()

        return HttpResponseRedirect(reverse('reviews:book_detail.html', args=(book.id,)))

    return render(request, 'reviews/book_detail.html', {'book': book, 'form': form})
    
def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':username}
    return render(request, 'reviews/user_review_list.html', context)
    

bookrevs/reviews/templates/reviews/book_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}

<h2>{{ book.name }}</h2>
<h3>{{ book.author }} </h3>

<h5>{{ book.review_set.count }} reviews ({{ wine.average_rating | floatformat }} average rating)</h5>

<h3>Recent reviews</h3>

{% if book.review_set.all %}

<div>

    {% for review in book.review_set.all %}

    <div>

        <em>{{ review.comment }}</em>

        <h6>Rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>

        <h5><a href="{% url 'reviews:review_detail' review.id %}">

        Read more

        </a></h5>

    </div>

    {% endfor %}

</div>

{% else %}

<p>No reviews for this book yet</p>

{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' book.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>

{% endblock %}

bookrevs/reviews/templates/reviews/book_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}

<h2>Book list</h2>



{% if book_list %}

<div>

    {% for book in book_list %}

    <div>

        <h4><a href="{% url 'reviews:book_detail' book.id %}">
        {{ book.name }}

        </a>by {{ book.author }}</h4>
        <h5>{{ book.review_set.count }} reviews</h5>
        <h5>{{ book.average_rating | floatformat }} average rating</h5>

    </div>

    {% endfor %}

</div>

{% else %}

    <p>No books are available.</p>

{% endif %}

{% endblock %}

bookrevs/reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block title %}
<h2><a href="{% url 'reviews:book_detail' review.book.id %}">{{ review.book.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated <b>{{ review.rating }} of 5</b> by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p><i>{{ review.comment }}</i></p>
{% endblock %}

bookrevs/reviews/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}

<h2>List of Reviews</h2>

{% endblock %}

{% block content %}
{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.book.name }}
        </a></h4>
        <h5>{{ review.book.author }} </h5>
        <h6>Rated <b>{{ review.rating }} of 5 </b> by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <p><i>{{ review.comment }}</i></p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}

{% endblock %}

bookrevs/reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ user.username }}</h2>
{% endblock %}

bookrevs/templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
    
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Book Reviews</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:book_list' %}">Book List</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}